---
services:
  jenkins:
    build: ./images/jenkins
    restart: on-failure
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    group_add:
     - "998"
    networks:
      - default
      - ingress
    labels:
      - traefik.enable=true
      - traefik.http.routers.jenkins.rule=Host(`jenkins.l3mpire.localhost`)

volumes:
  jenkins_home:

networks:
  default:
  ingress:
    external: true
    name: traefik_default
