---
services:
  main:
    image: logan.test.lem.ovh/node-app
    networks:
      - ingress
    labels:
      - traefik.enable=true
      - traefik.http.routers.${COMPOSE_PROJECT_NAME}.rule=Host(`logan.test.lem.ovh`)

networks:
  ingress:
    external: true
    name: traefik_default
