pipeline {
    agent any

    options {
        //FIXME Disabled for test purpose
        // buildDiscarder(
        //     logRotator(
        //         daysToKeepStr: '5',
        //         numToKeepStr: '10',
        //     )
        // )

        disableConcurrentBuilds()
        timeout(time: 10, unit: 'MINUTES')
        timestamps()
        disableRestartFromStage()
    }

    stages {
        stage('Build') {
            agent {
                docker {
                    image 'node:20.12.0'
                    reuseNode true
                }
            }

            steps {
                dir('applications/node-app') {
                    sh 'npm ci'
                    sh 'npm run lint'
                }
            }
        }

        stage('Publish') {
            steps {
                dir('applications/node-app') {
                    script {
                        docker.build('logan.test.lem.ovh/node-app')
                    }
                }
            }
        }

        stage('Deploy') {
            steps {
                dir('applications/node-app/docker-compose') {
                    sh 'docker compose --project-name node-app-default up --force-recreate --remove-orphans --detach'
                }
            }
        }
    }
}
