---
services:
  main:
    image: traefik:2.11.0
    restart: always
    ports:
    - 80:80
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./files/main/etc:/etc/traefik
    networks:
    - default

networks:
  default:
    driver: bridge
